//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ZeyrekWeb.NotificationWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ReadNotificationsSoap", Namespace="http://tempuri.org/")]
    public partial class ReadNotifications : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZReadNotificationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ReadNotifications() {
            this.Url = global::ZeyrekWeb.Properties.Settings.Default.ZeyrekWeb_NotificationWebReference_ReadNotifications;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZReadNotificationCompletedEventHandler ZReadNotificationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ZReadNotification", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ZNotification[] ZReadNotification(System.DateTime Date_, string user) {
            object[] results = this.Invoke("ZReadNotification", new object[] {
                        Date_,
                        user});
            return ((ZNotification[])(results[0]));
        }
        
        /// <remarks/>
        public void ZReadNotificationAsync(System.DateTime Date_, string user) {
            this.ZReadNotificationAsync(Date_, user, null);
        }
        
        /// <remarks/>
        public void ZReadNotificationAsync(System.DateTime Date_, string user, object userState) {
            if ((this.ZReadNotificationOperationCompleted == null)) {
                this.ZReadNotificationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZReadNotificationOperationCompleted);
            }
            this.InvokeAsync("ZReadNotification", new object[] {
                        Date_,
                        user}, this.ZReadNotificationOperationCompleted, userState);
        }
        
        private void OnZReadNotificationOperationCompleted(object arg) {
            if ((this.ZReadNotificationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZReadNotificationCompleted(this, new ZReadNotificationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ZNotification {
        
        private int idField;
        
        private string titleField;
        
        private string commentField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private int repeatPeriodField;
        
        private string groupOrUserField;
        
        private string notificationGroupField;
        
        private System.DateTime showDateField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public int RepeatPeriod {
            get {
                return this.repeatPeriodField;
            }
            set {
                this.repeatPeriodField = value;
            }
        }
        
        /// <remarks/>
        public string GroupOrUser {
            get {
                return this.groupOrUserField;
            }
            set {
                this.groupOrUserField = value;
            }
        }
        
        /// <remarks/>
        public string NotificationGroup {
            get {
                return this.notificationGroupField;
            }
            set {
                this.notificationGroupField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ShowDate {
            get {
                return this.showDateField;
            }
            set {
                this.showDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ZReadNotificationCompletedEventHandler(object sender, ZReadNotificationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZReadNotificationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZReadNotificationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZNotification[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZNotification[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591