//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ZeyrekWeb.PasswordWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PasswordOperationsSoap", Namespace="http://tempuri.org/")]
    public partial class PasswordOperations : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback setPasswordQOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPasswordQOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PasswordOperations() {
            this.Url = global::ZeyrekWeb.Properties.Settings.Default.ZeyrekWeb_PasswordWebReference_PasswordOperations;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event setPasswordQCompletedEventHandler setPasswordQCompleted;
        
        /// <remarks/>
        public event getPasswordQCompletedEventHandler getPasswordQCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setPasswordQ", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool setPasswordQ(string username, string question1, string question2, string question3, string answer1, string answer2, string answer3) {
            object[] results = this.Invoke("setPasswordQ", new object[] {
                        username,
                        question1,
                        question2,
                        question3,
                        answer1,
                        answer2,
                        answer3});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void setPasswordQAsync(string username, string question1, string question2, string question3, string answer1, string answer2, string answer3) {
            this.setPasswordQAsync(username, question1, question2, question3, answer1, answer2, answer3, null);
        }
        
        /// <remarks/>
        public void setPasswordQAsync(string username, string question1, string question2, string question3, string answer1, string answer2, string answer3, object userState) {
            if ((this.setPasswordQOperationCompleted == null)) {
                this.setPasswordQOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetPasswordQOperationCompleted);
            }
            this.InvokeAsync("setPasswordQ", new object[] {
                        username,
                        question1,
                        question2,
                        question3,
                        answer1,
                        answer2,
                        answer3}, this.setPasswordQOperationCompleted, userState);
        }
        
        private void OnsetPasswordQOperationCompleted(object arg) {
            if ((this.setPasswordQCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setPasswordQCompleted(this, new setPasswordQCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPasswordQ", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ZPassword getPasswordQ(string username) {
            object[] results = this.Invoke("getPasswordQ", new object[] {
                        username});
            return ((ZPassword)(results[0]));
        }
        
        /// <remarks/>
        public void getPasswordQAsync(string username) {
            this.getPasswordQAsync(username, null);
        }
        
        /// <remarks/>
        public void getPasswordQAsync(string username, object userState) {
            if ((this.getPasswordQOperationCompleted == null)) {
                this.getPasswordQOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPasswordQOperationCompleted);
            }
            this.InvokeAsync("getPasswordQ", new object[] {
                        username}, this.getPasswordQOperationCompleted, userState);
        }
        
        private void OngetPasswordQOperationCompleted(object arg) {
            if ((this.getPasswordQCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPasswordQCompleted(this, new getPasswordQCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ZPassword {
        
        private int idField;
        
        private string userNameField;
        
        private string question1Field;
        
        private string question2Field;
        
        private string question3Field;
        
        private string answer1Field;
        
        private string answer2Field;
        
        private string answer3Field;
        
        private System.DateTime setTimeField;
        
        private System.DateTime getTimeField;
        
        private int falseRequestCountField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Question1 {
            get {
                return this.question1Field;
            }
            set {
                this.question1Field = value;
            }
        }
        
        /// <remarks/>
        public string Question2 {
            get {
                return this.question2Field;
            }
            set {
                this.question2Field = value;
            }
        }
        
        /// <remarks/>
        public string Question3 {
            get {
                return this.question3Field;
            }
            set {
                this.question3Field = value;
            }
        }
        
        /// <remarks/>
        public string Answer1 {
            get {
                return this.answer1Field;
            }
            set {
                this.answer1Field = value;
            }
        }
        
        /// <remarks/>
        public string Answer2 {
            get {
                return this.answer2Field;
            }
            set {
                this.answer2Field = value;
            }
        }
        
        /// <remarks/>
        public string Answer3 {
            get {
                return this.answer3Field;
            }
            set {
                this.answer3Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SetTime {
            get {
                return this.setTimeField;
            }
            set {
                this.setTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime GetTime {
            get {
                return this.getTimeField;
            }
            set {
                this.getTimeField = value;
            }
        }
        
        /// <remarks/>
        public int FalseRequestCount {
            get {
                return this.falseRequestCountField;
            }
            set {
                this.falseRequestCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void setPasswordQCompletedEventHandler(object sender, setPasswordQCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setPasswordQCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setPasswordQCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getPasswordQCompletedEventHandler(object sender, getPasswordQCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPasswordQCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPasswordQCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZPassword Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZPassword)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591